### PR TITLE
Allow setting metricsBindAddress

### PR DESCRIPTION
**Pull request by TJM**
This allows the ability to override the metricsBindAddress, which is currently hard coded to 127.0.0.1. This does not change the default, but allows it to be set.

Tommy

### CODE REVIEW

**Comment by sheenaajay** [comment]
@TJM Thanks for submitting the PR. Changes look good. Could you please add a unit test to verify the changes. Thank you.

**Comment by TJM** [comment]
I am not great at unit tests (never really saw the point of testing the functionality of the language), but I can try. :-/

**Comment by sheenaajay** [comment]
@TJM thanks for the quick response. Running the changes on Adhoc pipeline. Will merge them as soon as the runs finish successfully.

**Comment by sheenaajay** [comment]
Screen Shot 2020-01-21 at 09 36 53

**Pull request merged**
