### PR TITLE
(maint) Updated .sync.yml

### PR DESCRIPTION
**Pull request by bmjen**
Update .sync.yml to remove duplicate dependency declarations
and switched to using the puppet-module-gems.
Also includes subsequent PDK template changes.

### CODE REVIEW

**Comment by sheenaajay** [comment]
@bmjen  Thanks Bryan. Looks good. Now we dont have to manually edit the Gemfile and travis.yml file.pdk update can be done for subsequent releases.
Could you please add the exclude directories to the .rubocop.yml file since the rubocop validation is failing.

**Comment by bmjen** [comment]
I've updated the .sync.yml to override the template defaults and you now don't have to manually reconfigure things.

/cc @sheenaajay @HelenCampbell

**Comment by sheenaajay** [comment]
@bmjen +1 thank you

**Pull request merged**
