### PR TITLE
implement crio support

### LINKED ISSUE #177: Adding Cri-o  support
My Company is using this module and we use crio as container runtime, I did a bunch of patches and would be happy to add the support to the module. Due to mentions this module is internally under heavy reconstruction, let me know if its currently a good point to file such a big PR.

### PR DESCRIPTION
**Pull request by SimonHoenscheid**
fixes #177

### CODE REVIEW

**Comment by sheenaajay** [comment]
Thanks for submitting the PR @SimonHoenscheid .It will be great of you can add acceptance test to test the container crio.

**Comment by SimonHoenscheid** [comment]
@sheenaajay I will add the tests

**Comment by sheenaajay** [comment]
Thanks alot @SimonHoenscheid

**Comment by SimonHoenscheid** [comment]
I would love to use kream for this, but the master seems to be broken

https://github.com/puppetlabs/kream/issues/26

**Comment by sheenaajay** [comment]
@SimonHoenscheid Apologies for the delay. We will take a look into kream issue. Thank you.

**Comment by sheenaajay** [comment]
@SimonHoenscheid Looks like kream is working. Could you please check it. Thank you.

**Comment by michaeltlombardi** [comment]
Since this hasn't seen any activity in about four months, I'm going to go ahead and close this pull request for the time being. Please re-open this pull request once the next actions are addressed, new information is available, or you have a question related to this pull request. We've become aware of difficulties re-opening pull requests, in the event you cannot please mention `puppetlabs/modules`  with an @ sign in front and we'll re-open this pull request.

Closing the pull request doesn't mean we don't consider this change valuable, just that there are things that need to be addressed before it can be merged. If you have any questions or concerns, please don't hesitate to ping us in slack.puppet.com.

**Pull request closed without merging**
