### PR TITLE
manage etcd client certificates even if etcd is not managed

### PR DESCRIPTION
**Pull request by ynnt**
Currently, kubeadm fails because etcd client certificates are not installed when mange_etcd set to false. That pushes customers to add these files externally which is not the best option, because SSL directory is managed with this module.

What I think is that this module should still manage etcd client certificates, because these PKI files are the requirement of kubeadm.

### CODE REVIEW

**Comment by carabasdaniel** [comment]
Hello @ynnt,

This seems like a valid point and I'm curious how other people manage their etcd client certificates when manage_etcd is set to false.

We are currently in the middle of a release of this module, but we will start testing it and hopefully get it merged for the future release. 

Thank you for your contribution.

**Comment by ynnt** [comment]
any chance to get this merged?

**Comment by sheenaajay** [comment]
@ynnt Apologies for the delay. Could you please rebase with the latest master since the Adhoc test suites are failing.Thank you.

**Comment by sheenaajay** [comment]
@ynnt Thank you.It looks like its showing all the commits from the master after the rebase.
Could you please do clean rebase and force push. Thank you.

**Comment by michaeltlombardi** [comment]
Since this hasn't seen any activity in about four months, I'm going to go ahead and close this pull request for the time being. Please re-open this pull request once the next actions are addressed, new information is available, or you have a question related to this pull request. We've become aware of difficulties re-opening pull requests, in the event you cannot please mention `puppetlabs/modules`  with an @ sign in front and we'll re-open this pull request.

Closing the pull request doesn't mean we don't consider this change valuable, just that there are things that need to be addressed before it can be merged. If you have any questions or concerns, please don't hesitate to ping us in slack.puppet.com.

**Pull request closed without merging**
