### PR TITLE
pass node_label to node_name for init/join

### PR DESCRIPTION
**Pull request by jorhett**
I'm not certain what the logic is, but there's an initialized input `node_name` which is now being passed to init/join which isn't set by anything. This doesn't work for AWS environments because we must pass in the hostname from instance data.

The attached patch solves the problem for me, but it's a hack. What's the difference between `node_name` and `node_label`? What was the goal here? 

For AWS I need to send you a patch that overrides the hostname with the instance name anyway, for this reason:

```
19s         Normal    RegisteredNode             Node        Node normalhostname.example.com event: Registered Node normalhostname.example.com in Controller
18s         Normal    DeletingNode               Node        Node normalhostname.example.com event: Deleting Node normalhostname.example.com because it's not present according to cloud provider
```

### CODE REVIEW

**Comment by jorhett** [comment]
I understand we can pass this in:

```
kubernetes::kubeadm_join::node_name: ip-10-206-5-185.instances.ec2
```

But I would like an answer on the what is intended by node_label, as it's passed in various commands which will fail if we don't set both the same.

```
  $unless_join = "kubectl get nodes | grep ${node_label}"
```

**Comment by davejrt** [comment]
This appears to be a bug, and we should just be using a single param for the title of the define and as the --node-name flag in the init/join command and config files. I'd prefer to raise a ticket internally and fix our own mistake rather than accepting (an albeit working hack) and put that into the next release.

**Comment by jorhett** [comment]
Not sure I understand. Are you suggesting I revised my PR to just pass `label` to `name` ?  That would work.

**Comment by jorhett** [comment]
I *think* I did what you were suggesting. Let me know.

**Comment by davejrt** [comment]
Closing as obsoleted by #223

**Pull request closed without merging**
