### PR TITLE
Add_support_1.16

### PR DESCRIPTION
**Pull request by BaronMsk**

### CODE REVIEW

**Comment by lionce** [comment]
Hello @BaronMsk ,

Would you please rebase your PR with the latest changes from master? Thanks

Cheers!

**Comment by BaronMsk** [comment]
Hello @lionce, Done

**Comment by nickperry** [comment]
Wouldn't ```$config_version = $kubernetes_version ? {
    /1.1(0|1)/ => 'v1alpha1',
    /1.12/     => 'v1alpha3',
    /1.1(3|4|5)/ => 'v1beta1',
    default    => 'v1beta2',
  } ``` have been a better implementation?

**Comment by BaronMsk** [comment]
@nickperry not a bad...

**Pull request merged**
