### PR TITLE
add new parameter kube_proxy_enable

### PR DESCRIPTION
**Pull request by BaronMsk**
Add option to disable kube proxy deployment

### CODE REVIEW

**Review by ybolotnikov — APPROVED** [review]

**Comment by LukasAud** [comment]
Hey @BaronMsk, could you add a description to your PR? We need to know what is it you are trying to fix/add and the reason behind it. That should help us evaluate faster your request. Also, please note that our integration testing is currently in red on our end, however, spec test failures should be addressed.

Sorry for the inconvenience.

**Comment by BaronMsk** [comment]
@LukasAud done

**Comment by jordanbreen28** [comment]
@BaronMsk seems you have some failing spec tests, can you address these?
I would say its beneficial to add some spec testing for this change to.
Thanks for all your work

**Comment by jordanbreen28** [comment]
Hey @BaronMsk, are you able to address the merge conflicts/failing tests?
Thanks

**Pull request closed without merging**
