### PR TITLE
Pin versions of debian packages

### PR DESCRIPTION
**Pull request by admont**
* Pin versions of `docker-engine`, `kubelet`, `kubectl` and `kubernetes-cni` packages.
* Parametrize CNI and Docker package names and versions.
* Cover with unit tests.
* Update documentation.

### CODE REVIEW

**Comment by scotty-c** [comment]
@admont This PR looks good. The only thing we did is actually not add the Docker version as a param. Only that it could allow a user to run a version of Docker that has not been verified by the Kubernetes project. Which could cause support issues on our side. The idea behind hardcoding the version was to allow us to test the version of Docker that works with the widest range of Kubernetes versions. What value would the end user get from adding the Docker version as a param?

**Comment by admont** [comment]
I see a few reasons. At a moment current versions are: K8s - v1.9.2, Docker - v.1.12.0-x, K8s Puppet module - v1.0.3.
1. Lets say with Puppet module v1.1.0 you are going to upgrade K8s to v1.10.0 and Docker to v.1.13.0-x. But also you fix some bugs and bring new futures. So users would like to have the new version but enterprise users usually prefer to stay with older versions of software - K8s, Docker, CNI, etc.
2. Lets say Debian release a new version of Docker package v.1.12.0-y in some reason. Which doesn't work correctly in users environment. Until Debian release another version of package with fix user most likely prefer to stay with v.1.12.0-x.
3. In some reason user prefer to stay with Docker version v.1.12.0-x but with new K8s version, maybe because of application implementation or CI tools.

**Comment by scotty-c** [comment]
@admont would you please rebase this PR against master due to merging #82 
Thanks in advance

**Comment by admont** [comment]
Rebase is done

**Comment by scotty-c** [comment]
@admont I will check this out in the next 24 hours

**Comment by admont** [comment]
Thanx!
Back to question regarding docker version as a parameter. According K8s [documentation](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.9.md) the validated docker versions are 1.11.2 to 1.13.1 and 17.03.x. So it is not one binded version. Any way [#82](https://github.com/puppetlabs/puppetlabs-kubernetes/pull/82) already have docker version as parameter.

**Comment by admont** [comment]
@scotty-c any news?

**Comment by scotty-c** [comment]
@admont I will have a look at this one tomorrow. Sorry I have been in transit from Sydney to Belfast

**Comment by scotty-c** [comment]
@admont Thanks for a great PR

**Pull request merged**
