### PR TITLE
Disable swap permanently

### PR DESCRIPTION
**Pull request by scoopex**
This solves #365

Remove swapspace entries from /etc/fstab.

### CODE REVIEW

**Comment by scoopex** [comment]
Sorry, i was not successful in executing the litmus tests described in the "Development" section on my ubuntu 18.04 system. "litmus:install_module" dropped very cryptic messages which were not understandable for a litmus newbie.... (see #419)
So probably you can fix potential acceptance test problems to get these useful changes to upstream?

**Comment by scoopex** [comment]
Feedback or merge would be nice :-)

**Comment by scoopex** [comment]
Which is worse for this puppet module? No feedback for pullrequests and mergerequests to leave open forever or to apply corrections that have not been reviewed extensively? The current situation is not really satisfying for contributors.

**Comment by david22swan** [comment]
@scoopex 
Making a quick change to point this PR towards the newly defined default main branch as part of our work to remove inappropriate terminology. Apologies if this is inconvenient in any way.

**Pull request merged**
