### PR TITLE
Fix calico-tigera installation problems

### PR DESCRIPTION
**Pull request by jorhett**
### Update network preinstall and provider target URLs. Current ones return

```
Notice: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network (preinstall)]/returns: error: unable to read URL "https://docs.projectcalico.org/manifests/tigera-operator.yaml", server reported 404 Not Found, status code=404
Error: '["kubectl", "apply", "-f", "https://docs.projectcalico.org/manifests/tigera-operator.yaml"]' returned 1 instead of one of [0]
Error: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network (preinstall)]/returns: change from 'notrun' to ['0'] failed: '["kubectl", "apply", "-f", "https://docs.projectcalico.org/manifests/tigera-operator.yaml"]' returned 1 instead of one of [0]
Warning: Private key for 'test.foo.bar' does not exist
Warning: Client certificate for 'test.foo.bar' does not exist
Error: /Stage[main]/Kubernetes::Kube_addons/File[/etc/kubernetes/calico-installation.yaml]: Could not evaluate: Could not retrieve information from environment production source(s) https://docs.projectcalico.org/manifests/custom-resources.yaml
```

Found problem reported in projectcalico/calico#7300
Documentation now shows the raw URLs for the explicit version being used https://docs.tigera.io/calico/3.26/getting-started/kubernetes/quickstart#install-calico

### Use `kubectl create` to avoid metadata length limitations

Sourced from upstream projectcalico/calico#6811 and docs at https://docs.tigera.io/calico/3.26/getting-started/kubernetes/quickstart#install-calico

### CODE REVIEW

**Comment by jorhett** [comment]
I overlooked that this overlaps with #617, should probably be combined.

**Comment by jordanbreen28** [comment]
@jorhett some of this work was merged in with https://github.com/puppetlabs/puppetlabs-kubernetes/pull/625, are you able to refer to this, rebase and check if anything extra from your implementation is needed? 
Thanks for your work on this! 🚀

**Comment by jordanbreen28** [comment]
did you get the chance to review the comment above @jorhett ?

**Comment by jorhett** [comment]
I've rebased from main as of today. All of the problems I originally reported remain unfixed so this PR remains valid.

**Comment by deric** [comment]
@jorhett Please, update the specs accordingly, e.g. [apply -> create](https://github.com/puppetlabs/puppetlabs-kubernetes/blob/main/spec/classes/kube_addons_spec.rb#L76)

**Review by deric — APPROVED** [review]

**Comment by jorhett** [comment]
@deric should I assume you'll merge this when ready for the next release?

**Pull request merged**
