### PR TITLE
improve package installation and dashboard installation

### PR DESCRIPTION
**Pull request by scoopex**
improve package installation

 - add option for package pinning on debian
 - change default for debian cgroup_driver to systemd according to
    https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker
 - adapt an enhance tests for the changes above

fix 2.0 dashboard installation
    
    - 2.0 dashboard moved from kube-system
      to kubernetes-dashboard namespace
    - improve node readyness check
      (check if really all nodes are ready)

### CODE REVIEW

**Comment by scoopex** [comment]
I think this pull request might solve https://github.com/puppetlabs/puppetlabs-kubernetes/issues/339

**Comment by scoopex** [comment]
This pull request might also solve https://github.com/puppetlabs/puppetlabs-kubernetes/issues/341 for ubuntu. Probably we can also add a functionality like this for centos/redhat.

**Comment by scoopex** [comment]
waiting for comments :-)

**Comment by florindragos** [comment]
Hey @scoopex,
Thanks for your contribution.
I've ran the acceptance tests and they passed on ubuntu 16.04 but failed on redhad and centos 7.

```17:32:05         puppet apply --verbose --detailed-exitcodes /tmp/apply_manifest.pp.sWk4Tu
17:32:05        Last 10 lines of output were:
17:32:05        	Error: /Stage[main]/Kubernetes::Cluster_roles/Kubernetes::Kubeadm_init[shrewd-guise]/Kubernetes::Wait_for_default_sa[default]/Exec[wait for default serviceaccount creation in default]/returns: change from 'notrun' to ['0'] failed: 'kubectl -n default get serviceaccount default -o name' returned 1 instead of one of [0]
17:32:05        	Notice: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]: Dependency Exec[kubeadm init] has failures: true
17:32:05        	Notice: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]: Dependency Exec[wait for default serviceaccount creation in default] has failures: true
17:32:05        	Info: Class[Kubernetes]: Unscheduling all events on Class[Kubernetes]
17:32:05        	Info: Stage[main]: Unscheduling all events on Stage[main]
17:32:05        	Warning: /Stage[main]/Kubernetes::Kube_addons/Exec[Install cni network provider]: Skipping because of failed dependencies
17:32:05        	Warning: /Stage[main]/Kubernetes::Kube_addons/Exec[schedule on controller]: Skipping because of failed dependencies
17:32:05        	Warning: /Stage[main]/Kubernetes::Kube_addons/Exec[Install Kubernetes dashboard]: Skipping because of failed dependencies
17:32:05        	Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
17:32:05        	Notice: Applied catalog in 191.77 seconds
17:32:05        
17:32:05      # ./.bundle/gems/gems/beaker-4.14.0/lib/beaker/host.rb:391:in `exec'
17:32:05      # ./.bundle/gems/gems/beaker-4.14.0/lib/beaker/dsl/helpers/host_helpers.rb:83:in `block in on'
17:32:05      # ./.bundle/gems/gems/beaker-4.14.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
17:32:05      # ./.bundle/gems/gems/beaker-4.14.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
17:32:05      # ./.bundle/gems/gems/beaker-4.14.0/lib/beaker/dsl/helpers/host_helpers.rb:63:in `on'
17:32:05      # ./.bundle/gems/gems/beaker-puppet-1.18.8/lib/beaker-puppet/helpers/puppet_helpers.rb:529:in `block in apply_manifest_on'
17:32:05      # ./.bundle/gems/gems/beaker-4.14.0/lib/beaker/shared/host_manager.rb:130:in `run_block_on'
17:32:05      # ./.bundle/gems/gems/beaker-4.14.0/lib/beaker/dsl/patterns.rb:37:in `block_on'
17:32:05      # ./.bundle/gems/gems/beaker-puppet-1.18.8/lib/beaker-puppet/helpers/puppet_helpers.rb:457:in `apply_manifest_on'
17:32:05      # ./.bundle/gems/gems/beaker-puppet-1.18.8/lib/beaker-puppet/helpers/puppet_helpers.rb:536:in `apply_manifest'
17:32:05      # ./spec/acceptance/kubernetes_spec.rb:35:in `block (5 levels) in <top (required)>'```

**Comment by scoopex** [comment]
Hmm, i grepped for "shrewd-guise" in the module code.
It seems that these acceptance tests are not part of the repository.

Where can i find them, and can setup and test it locally in acceptable effort?

Probably the classes "kubernetes::wait_for_default_sa" and "kubernetes::kubeadm_init" just need a readyness check like in "kube_addons.pp"
```
$node_ready_command = "kubectl get nodes|egrep -v  'NAME|Ready'|egrep '.*'"
```

**Comment by florindragos** [comment]
This is the apply that is failing: https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/spec/acceptance/kubernetes_spec.rb#L35
I assume "shrewd-guise" is something generated.

Not sure if you can run the acceptance tests yourself. There is a vagrant beaker nodeset present, but it looks pretty old. We are running the tests on vmpooler but we are currently working on providing an easy way to test against vagrant locally.

**Comment by scoopex** [comment]
> This is the apply that is failing: https://github.com/puppetlabs/puppetlabs-kubernetes/blob/master/spec/acceptance/kubernetes_spec.rb#L35
> I assume "shrewd-guise" is something generated.
> 
> Not sure if you can run the acceptance tests yourself. There is a vagrant beaker nodeset present, but it looks pretty old. We are running the tests on vmpooler but we are currently working on providing an easy way to test against vagrant locally.

I think the modifications of my pull request are important for users of the module.
We should not keep the addressed problem unsolved for a long time....

Whats the next step to get this merged? Can anybody with access to the acceptance tests fix the tests or the implementation or at leas give feedback what goes wrong?

**Comment by carabasdaniel** [comment]
Hello @scoopex, you can grab the PR from here https://github.com/puppetlabs/puppetlabs-kubernetes/pull/353 and run the acceptance tests locally using Vagrant. In the README.md you will find information on how to do that. It would be really great to get this merged.

**Comment by scoopex** [comment]
> Hello @scoopex, you can grab the PR from here #353 and run the acceptance tests locally using Vagrant. In the README.md you will find information on how to do that. It would be really great to get this merged.

Ah thats cool. I never used litmus before probably it is a good thing to add some documentation to this PR informs the user that there are acceptance tests and how to run them.

**Comment by sheenaajay** [comment]
Thanks for the great PR @scoopex. Readme is updated with instructions on how to run the acceptance tests. Could you please resolve conflicts and rebase with the latest master. Thank you.

**Comment by scoopex** [comment]
- rebased my changes to the upstream master
- minor bugfix, docker daemon.json.erb generated a broken syntax for json files
- i have currently now project time/resources to run the litmus tests but the changes work in our entvironment and the testcases are ok.
- probably somebody of you, can verify that everything is ok in the litmus teststs

**Comment by scoopex** [comment]
https://github.com/puppetlabs/puppetlabs-kubernetes/issues/399

**Comment by sheenaajay** [comment]
@scoopex Please find the instruction on running tests using litmus here https://github.com/puppetlabs/puppet_litmus/wiki

`bundle install`
`bundle exec rake 'litmus:provision[vagrant, ubuntu/xenial64]'`
`bundle exec rake litmus:install_agent`
`bundle exec rake litmus:install_module`
`bundle exec rake litmus:acceptance:parallel`

Please let us know if you need more information.

**Comment by scoopex** [comment]
@sheenaajay i closed that pull request because the git history was a bit messed up and partial contents of this PR were already applied.

I created a new PR with a single commit: https://github.com/puppetlabs/puppetlabs-kubernetes/pull/416

**Pull request closed without merging**
