### PR TITLE
Allow etcd to be installed through system packages

### PR DESCRIPTION
**Pull request by ralphje**
In restricted/airgapped systems, using etcd that is to be downloaded from the internet may be hard. In some operating systems, e.g. Debian, etcd-server is available from the package repositories. This commit adds two settings (etcd_install_method and etcd_package_name) to allow installing etcd through system packages.

### CODE REVIEW

**Comment by scotty-c** [comment]
@ralphje we are internally doing some work to increase functionality around etcd configuration. So I am going to leave this PR open and wait to get that work into master. Then we can have a look at this PR then

**Comment by davejrt** [comment]
@ralphje apologies for the delay in getting back to you on this. We've had some conversations internally about how to best approach this, and I'd like to see this PR merged. Unfortunately there are some merge conflicts with the recent updates that need to be resolved before I can merge. 

Would you consider rebasing and fixing the conflicts?

**Comment by ralphje** [comment]
I have rebased the commit.

**Comment by ralphje** [comment]
@davejrt So, having rebased my PR, following your comment, I had expected it to have been merged by now. What happened? :(

**Comment by davejrt** [comment]
Apologies @ralphje. I believe another PR got merged and then caused another conflict with your changes and I never followed up with you again. 

That's on me, and certainly not a reflection of the effort you've made with this PR.

**Comment by gregohardy** [comment]
LGTM

**Pull request merged**
