### PR TITLE
fix cluster readiness check in 0.2.0

### PR DESCRIPTION
**Pull request by juckerf**
fix exec resource which waits for the cluster to become ready

### CODE REVIEW

**Comment by scotty-c** [comment]
@juckerf What was the reason for changing this from the original exec?

**Comment by juckerf** [comment]
@scotty-c 
sorry for the missing explanation.

if my understanding of the puppet `Exec` resource is correct, it throws an error if the return code of the exec command is not 0. Therefore, if all nodes are ready the `grep` in the original exec command returns not 0 and the `Exec` fails.

**Comment by scotty-c** [comment]
@juckerf This is an interesting one, If we use CNI as the network interface the cluster should never be in a ready state until the networking is installed. So this is by design that the exec fails if the cluster is ready before the networking is installed.

**Comment by scotty-c** [comment]
Thanks for your contribution but we have chosen to support the CNI interface only. So we will not be merging this

**Pull request closed without merging**
