### PR TITLE
Build config file for worker nodes too

### PR DESCRIPTION
**Pull request by jorhett**
This resolves the same cloud_provider problem for workers as the previous patch.
It also does some strategic structure for the new config-file-oriented world,
which will hopefully make it easier to obsolete older versions with less pain.

I wouldn't merge this yet, I don't think it's been tested all the ways it needs to be. We need some eyeballs on this in different environments.

### CODE REVIEW

**Comment by davejrt** [comment]
I agree with the the changes you're proposing here, we've had internal discussions to do something similar with the use of config files for joining nodes with the newer versions of k8s. 

There's a few things in here that are broken like the config files and the define types but generally speaking the direction is one I support

**Comment by davejrt** [comment]
Have been testing this branch over the xmas/new year period and can't seem to get a clean run with kream on the worker nodes first go. I need to re run puppet, as it seems to skip over the unless statement the first time and not put any of the worker config down. 

Are you only working in AWS?

**Comment by jorhett** [comment]
Are you talking about this `unless`? https://github.com/puppetlabs/puppetlabs-kubernetes/pull/224/commits/513f9d64b7bcd0eba9ca214687e9ccce88a83bc4#diff-60ae41fd0a31977447947f59940ee9a4R444

I tested this in Kream with 1.10.2, 1.11.2, 1.12.3, 1.13.0 and 1.13.1 and I'm not seeing that problem. What does your test data look like?

**Comment by davejrt** [comment]
I tested this on aws with ubuntu and it worked fine. Still can't get it to work with vagrant using puppet5/6 on debian and ubuntu...very odd.

**Comment by jorhett** [comment]
I am gonna work on this, sorry, cycles have been hard to find last few days

**Comment by davejrt** [comment]
@jorhett no problem. Just to be clear the PR is good, and we have every intention of merging once we can hopefully figure out this small issue. I've had someone else test to make sure it's not my local environment with the same result. 

I am in the same boat in that I am working in the background whilst doing other things so let's post any results here and keep the conversation going

**Comment by davejrt** [comment]
I'm going to merge this, and raise a separate issue to track this as a big in KREAM only, as a release is dependent on this code and master is currently broken without it. Thanks again for your contributions

**Pull request merged**
