### PR TITLE
Package pinning and auto restart of etcd

### PR DESCRIPTION
**Pull request by scoopex**
This pull request adresses: #417 and #190.

Sorry, i was not successful in executing the litmus tests described in the "Development" section on my ubuntu 18.04 system. "litmus:install_module" dropped very cryptic messages which were not understandable for a litmus newbie.... (see #419)
So probably you can fix potential acceptance test problems to get these useful changes to upstream?

### CODE REVIEW

**Comment by scoopex** [comment]
Feedback or merge would be nice :-)

**Comment by scoopex** [comment]
> Feedback or merge would be nice :-)

Which is worse for this puppet module? No feedback for pullrequests and mergerequests to leave open forever or to apply corrections that have not been reviewed extensively? The current situation is not really satisfying for contributors.

**Comment by david22swan** [comment]
@scoopex 
Making a quick change to point this PR towards the newly defined default main branch as part of our work to remove inappropriate terminology. Apologies if this is inconvenient in any way.

**Comment by scoopex** [comment]
Great, thanks.

**Comment by daianamezdrea** [comment]
Hi @scoopex, could you please rebase this PR? Thank you!

**Comment by scoopex** [comment]
Rebased :-)

**Comment by sanfrancrisko** [comment]
Hi @scoopex - thanks for your patience; the team has been down on resources but up on work, unfortunately. We're trying to get back on top of things.

We're reviewing the changes on the PR at the moment, however, there seems to be some merge conflicts - would you be able to take a look at this?

**Comment by scoopex** [comment]
Sorry, i forgot that upstream/master is renamed to upstream/main :-)

**Comment by sanfrancrisko** [comment]
Hi @scoopex - we're hoping to get your PR over the line today. Again, thanks for your patience.

There were a few PRs merged in recently that are now causing conflicts on the branch. Could I ask you to kindly rebase with `puppetlabs/puppetlabs-kubernetes:main` again and we'll look to get our remaining testing done and the PR merged later today?

Many thanks!

**Comment by scoopex** [comment]
Rebased the branch. It seems that the conflicts were originated in the apply order of my various pull requests in combination with the puppetlabs code formatting rules which enforce large changesets almost every time  a developer touches the parameters of a class. 

I am now on holiday until 1.9.2020, so I will only be able to give feedback on questions after this date.

**Comment by sanfrancrisko** [comment]
Thanks @scoopex - we're hoping to get our own testing wrapped up today and the PR merged later. There's been a few environmental issues frustrating that process, at the moment.

Yeah, I noticed there was a lot of churn around the parameters. I was trying to resolve the conflicts myself, but, given the size of the PR, I thought it would be safer if you were to resolve them. Normally, if we have the cycles, we're happy to do that sort of stuff ourselves and not call on the original contributor.

If any change to the parameters is resulting in these sorts of changes then I'll raise a ticket to see if we can fix up the branch to a state that doesn't mean a load of churn on each PR.

**Pull request merged**
