### PR TITLE
kubernetes::cluster_roles - ignore CNI errors on `kubeadm join`

### PR DESCRIPTION
**Pull request by tskirvin**
k8s 1.10.2 has a bug in joining a cluster where `/var/run/dockershim.sock` doesn't yet exist but `kubeadm join` won't complete until it's there.  So we work around it by ignoring that missing file via `manifests/cluster_roles.pp`.

Also fixes a version number error in README.md.

### CODE REVIEW

**Comment by davejrt** [comment]
I just tried to test this in KREAM, and wasn't able to replicate the error. Is it specific to a version of docker or something else?

**Comment by tskirvin** [comment]
Apparently?  I'm running docker-engine-17.03.1.ce-1.el7.centos.x86_64 + flannel.  I found the bug report and fix in a random thread somewhere; this may have been it:

https://github.com/kubernetes-incubator/cri-tools/issues/153

I'd also settle for opening up a module parameter to list preflight errors to ignore, I suppose.  It's hard to tell what's the best level of complexity for this kind of thing.

**Comment by davejrt** [comment]
I think a parameter sounds like a good idea in this case.

**Comment by davejrt** [comment]
LGTM, thanks for your contribution

**Pull request merged**
