### PR TITLE
Configure image registry settings for  containerd when installed via package

### PR DESCRIPTION
**Pull request by andeman**
Configure registry mirros, tls and auth setting for containerd as described here: https://github.com/containerd/containerd/blob/master/docs/cri/registry.md#configure-image-registry

### CODE REVIEW

**Comment by andeman** [comment]
Hi,
could someone help me with execute the test locally?

What i tried:
```
pdk bundle exec rake 'litmus:provision_list[all_supported]'
bolt task run provision::fix_secure_path --inventory inventory.yaml --targets all --modulepath spec/fixtures/modules
pdk bundle exec rake 'litmus:install_agent[puppet6]'
pdk bundle exec rake litmus:install_module

Add roles in  Inventory.yaml :
    vars:
      role: controller

    vars:
      role: worker1

    vars:
      role: worker2
```

[litmus_error.txt](https://github.com/puppetlabs/puppetlabs-kubernetes/files/6163218/litmus_error.txt)

**Comment by daianamezdrea** [comment]
Hi @andeman, I tested locally your changes and the error from here is not there, if you go to Travis you'll see that the failling tests are from spec tests, so if you want to reproduce it locally you only need to run **bundle exec rake spec**, also, Travis was removed from our modules, can you rebase your PR? Thank you, let me know if I can help you with something else

**Comment by andeman** [comment]
Hi @daianamezdrea, 
i am able to execute the spec test locally. But the Integration test "Integration Testing / Integration (centos-7, puppet6-nightly)" is failing. And i tried to execute them locally wit the commands mentioned above. I have no clue, why this integration test is failing and i´m not able to execute them locally. Could you verfiy the integration test is working with the current main branch?

Thx

**Comment by daianamezdrea** [comment]
Hi @andeman, thank you for your work on the PR, I re-run the jobs because I was thinking that the error is not related with your PR and indeed it wasn't. You can check now the run and see that everything is fine. Monday is our Community Day and your PR will  be reviewed, cheers ! ( I'll change the readme to reflect our last changes and how you can run locally the tests)

**Comment by andeman** [comment]
Hi,
any updates on this issue?
Thanks

**Comment by daianamezdrea** [comment]
Hi @andeman, yes, I checked your changes today and everything is looking fine, sorry for taking me so long, I just wanted to be sure everything is fine before merging it! Thank you!

**Pull request merged**
